services:
  accounts:
    image: "pranav2299/accounts:docker"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hsbcbank
  loans:
    image: "pranav2299/loans:docker"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hsbcbank
  cards:
    image: "pranav2299/cards:docker"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hsbcbank
networks:
 hsbcbank:
    driver: "bridge"